name: Validation Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1

    - name: Run Tests
      working-directory: ./src
      run: dotnet test