name: Push NuGet Packages

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v3

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Get release tag
      id: getReleaseTag
      shell: bash
      run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

    - name: Build
      working-directory: ./src
      run: dotnet build -c Release -p:Version=${{ steps.getReleaseTag.outputs.VERSION }}

    - name: Push packages
      working-directory: ./src
      run: nuget push "**/*.nupkg" -Source nuget.org